services:
  - type: web
    name: secure-gig-guardian
    env: docker
    repo: https://github.com/ArjunJayakrishnan-codes/Suraksha-AI.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: "secure_gig_guardian"
      - key: MONGODB_COLLECTION
        value: "insurance_policies"
      - key: MONGODB_CLAIMS_COLLECTION
        value: "claims"
      - key: MONGODB_PAYOUTS_COLLECTION
        value: "payouts"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
